### ISSUE TITLE
Does not report errors in snippets

### ISSUE THREAD

**Issue by warpech** [alshakero/perf.zone#1]
When I use an unexisting function name, I get "0 op/second" as the result:

https://run.perf.zone/view/ES5-vs-ES6-functions-1500885371082

![screen shot 2017-07-24 at 10 37 08](https://user-images.githubusercontent.com/566463/28514949-28ad8a80-705c-11e7-8df0-cdf1ffbe7f2b.png)

**Comment by alshakero** [comment]
@warpech this issue warmed my heart. I'll look into it next weekend, thanks.

**Comment by alshakero** [comment]
![image](https://user-images.githubusercontent.com/17054134/28589235-8b2c5d68-717d-11e7-9d96-e783872230e5.png)

Closing as fixed. Thanks a million indeed.
